---
title: Andrey Kaipov
baseURL: https://kaipov.com
theme: leekh

params:
  resume: resume.pdf
  favicon: images/face-flipped.png
  profiles:
  - name: GitHub
    url: https://github.com/andreykaipov
  - name: LinkedIn
    url: https://linkedin.com/in/kaipov
  - name: Twitter
    url: https://twitter.com/andreykaipov

disableKinds:
- taxonomy
- term
- RSS
- sitemap
